In [53]:
import pandas as pd
import numpy as np
import datetime as dt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression 
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [54]:
train = pd.read_excel(r"G:\traindata\rxdata\rx_monthsale.xlsx")

In [55]:
train  = pd.DataFrame(train)#设定Xy及数据处理
X = train['months']
X = X.apply(pd.to_datetime)
X = X.map(dt.datetime.toordinal)
X = X.values.reshape(-1, 1)
y = train.iloc[:,-1]
y = y.values.reshape(-1, 1)
y


array([[2.00790205e+08],
       [7.79418931e+07],
       [1.67829894e+08],
       [1.42025210e+08],
       [2.15992239e+08],
       [1.87083979e+08],
       [1.91186605e+08],
       [2.19246672e+08],
       [2.22923424e+08],
       [2.27973832e+08],
       [2.81482146e+08],
       [2.26823412e+08],
       [2.97554480e+08],
       [1.40997438e+08],
       [3.22127121e+08],
       [2.11058314e+08],
       [1.93471693e+08],
       [2.60580823e+08],
       [2.05552688e+08],
       [2.44313645e+08],
       [2.76904498e+08],
       [2.14071061e+08],
       [3.22135162e+08],
       [3.12435070e+08],
       [1.65635393e+08],
       [1.66875324e+08],
       [2.34665377e+08],
       [1.97994950e+08]])

In [56]:
# scaler = MinMaxScaler() #实例化
# scaler = scaler.fit(y) #fit，在这里本质是生成min(x)和max(x)
# result = scaler.transform(y) #通过接口导出结果
# result
# y = result
# scaler = StandardScaler()#此处对数据进行标准化处理，使其符合
# result = scaler.fit_transform(y)
# result 
# y = result
# y

In [57]:
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X,y,test_size=0.3,random_state=445)#划分训练集和测试集

In [58]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=3,include_bias=False)#添加多项式回归，增加拟合程度，不生成与截距相乘的X0
Xtrain_poly = poly.fit_transform(Xtrain)#分别对训练集和测试集进行处理
Xtest_poly = poly.fit_transform(Xtest)#
X_poly = poly.fit_transform(X)

In [59]:
model = LinearRegression(normalize=True).fit(Xtrain_poly,Ytrain)
j = model.score(Xtest_poly,Ytest)
j

-0.2838231404546323

In [60]:
y_pre = model.predict(Xtest_poly)
Y_pre = model.predict(X_poly)

In [61]:
test= pd.read_excel(r"G:\traindata\rxdata\rx_test.xlsx")
test =pd.DataFrame(test)
pre_month = test['months']
pre_month = pre_month.apply(pd.to_datetime)
pre_month = pre_month.map(dt.datetime.toordinal)
pre_month = pre_month.values.reshape(-1, 1)
pre_month
pre_month_poly = poly.fit_transform(pre_month.reshape(-1,1))
pre_month_poly

array([[7.37607000e+05, 5.44064086e+11, 4.01305479e+17],
       [7.37614000e+05, 5.44074413e+11, 4.01316904e+17],
       [7.37638000e+05, 5.44109819e+11, 4.01356079e+17],
       [7.37669000e+05, 5.44155554e+11, 4.01406683e+17],
       [7.37699000e+05, 5.44199815e+11, 4.01455659e+17],
       [7.37730000e+05, 5.44245553e+11, 4.01506272e+17],
       [7.37760000e+05, 5.44289818e+11, 4.01555256e+17]])

In [62]:
y_predict = model.predict(pre_month_poly)
y_predict = y_predict.reshape(-1, 1)
y_predict = scaler.inverse_transform(y_predict)
y_predict

array([[1.38369131e+16],
       [1.37891051e+16],
       [1.36119723e+16],
       [1.33524401e+16],
       [1.30676574e+16],
       [1.27379304e+16],
       [1.23838570e+16]])

In [63]:
reg = LinearRegression().fit(Xtrain,Ytrain)