In [1]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
import pandas as pd
pd.DataFrame(data)

D:\anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [4]:
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [5]:
result_ = scaler.fit_transform(data)
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [6]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
scaler = MinMaxScaler(feature_range=[5,10])
result = scaler.fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [7]:
import numpy as np
X = np.array([[-1,2],[-0.5,6],[0,10],[1,18]])

X_nor = (X-X.min(axis=0))/(X.max(axis=0)-X.min(axis=0))
X_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [9]:
X_returned = X_nor*(X.max(axis=0) - X.min(axis=0)) + X.min(axis=0)
X_returned

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [10]:
from sklearn.preprocessing import StandardScaler
data = [[-1,2],[-0.5,6],[0,10],[1,18]]

scaler = StandardScaler()         #实例化此函数
scaler.fit(data)               #fit   实际生成均值与方差

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [13]:
scaler.mean_     #查看均值
scaler.var_      #查看方差

array([ 0.546875, 35.      ])

In [14]:
x_std=scaler.transform(data)  #通过接口导出结果

x_std.mean()               #结果为数组mean_查看均值
x_std.std()                #std查看方差

1.0

In [16]:
scaler.fit_transform(data) #也可一步达成结果

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [17]:
scaler.inverse_transform(x_std)         #使用此函数可以逆转标准化

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [1]:
import pandas as pd
data = pd.read_csv(r"D:\meachinelearn\菜菜sklearn\03数据预处理和特征工程\Narrativedata.csv",index_col = 0)
data.head(20)
# data.info()

Age     Sex Embarked Survived
0   22.0    male        S       No
1   38.0  female        C      Yes
2   26.0  female        S      Yes
3   35.0  female        S      Yes
4   35.0    male        S       No
5    NaN    male        Q       No
6   54.0    male        S       No
7    2.0    male        S       No
8   27.0  female        S      Yes
9   14.0  female        C      Yes
10   4.0  female        S  Unknown
11  58.0  female        S      Yes
12  20.0    male        S       No
13  39.0    male        S       No
14  14.0  female        S       No
15  55.0  female        S  Unknown
16   2.0    male        Q       No
17   NaN    male        S      Yes
18  31.0  female        S       No
19   NaN  female        C      Yes

In [53]:
Age = data.loc[:,"Age"].values.reshape(-1,1)
Age[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [nan],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [nan],
       [31.],
       [nan]])

In [60]:
imp_mean = imp_mean.fit_transform(Age)
imp_median = imp_median.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)

imp_mean[:20]
imp_median[:20]
imp_0[:20]

AttributeError: 'numpy.ndarray' object has no attribute 'fit_transform'

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [28.],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [28.],
       [31.],
       [28.]])

In [61]:
data.loc[:,"Age"] = imp_median          #此处使用中位数填补age
data.info()

Embarked = data.loc[:,"Embarked"].values.reshape(-1,1)
imp_mode = SimpleImputer(strategy="most_frequent")         #使用众数填写
data.loc[:,"Embarked"] = imp_mode.fit_transform(Embarked)     

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [22]:
# import pandas as pd
# data = pd.read_csv(r"D:\meachinelearn\菜菜sklearn\03数据预处理和特征工程\Narrativedata.csv",index_col = 0)
# data.head()

# data.loc[:,"Age"] = data.loc[:,"Age"].fillna(data.loc[:,"Age"].median())

# data.dropna(axis=0,inplace = True)                 #此处使用numpy和pandas填补更为简单  不是重点 先跳过

In [64]:
from  sklearn.preprocessing import LabelEncoder

y = data.iloc[:,-1]                               #输入标签

le = LabelEncoder()                              #实例化
le = le.fit(y)                                    #导入数据
label = le.transform(y)                           #transform接口调取结果

le.classes_                                     #查看有多少类别
# label

array([0, 1, 2])

In [65]:
# le.fit_transform(y)#也可以一步到位
# le.inverse_transform(label)#同时也可以反转回来

data.iloc[:,-1] = label        #让标签等于运行结果
data.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [66]:
from sklearn.preprocessing import OrdinalEncoder

data_ = data.copy()
data_.head()
OrdinalEncoder().fit(data_.iloc[:,1:-1]).categories_

data_.iloc[:,1:-1] = OrdinalEncoder().fit_transform(data_.iloc[:,1:-1])
data_.head()

Age  Sex  Embarked  Survived
0  22.0  1.0       2.0         0
1  38.0  0.0       0.0         2
2  26.0  0.0       2.0         2
3  35.0  0.0       2.0         2
4  35.0  1.0       2.0         0

In [2]:
data.head()
from sklearn.preprocessing import OneHotEncoder
x = data.iloc[:,1:-1]
x.head()

Sex Embarked
0    male        S
1  female        C
2  female        S
3  female        S
4    male        S

In [67]:
enc = OneHotEncoder(categories='auto').fit(x)
result = enc.transform(x).toarray()
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [68]:
# OneHotEncoder(categories='auto').fit_transform(X).toarray()           #依然可以直接一步到位，但为了给大家展示模型属性，所以还是写成了三步
# #依然可以还原
# pd.DataFrame(enc.inverse_transform(result))
# enc.get_feature_names()
# result
result.shape
newdata = pd.concat([data,pd.DataFrame(result)],axis=1) #axis=1,表示跨行进行合并，也就是将量表左右相连，如果是axis=0，就是将量表上下相连
newdata.head()
newdata.drop(["Sex","Embarked"],axis=1,inplace=True)
newdata.columns = ["Age","Survived","Female","Male","Embarked_C","Embarked_Q","Embarked_S"]
newdata.head() 

Age  Survived  Female  Male  Embarked_C  Embarked_Q  Embarked_S
0  22.0         0     0.0   1.0         0.0         0.0         1.0
1  38.0         2     1.0   0.0         1.0         0.0         0.0
2  26.0         2     1.0   0.0         0.0         0.0         1.0
3  35.0         2     1.0   0.0         0.0         0.0         1.0
4  35.0         0     0.0   1.0         0.0         0.0         1.0

In [70]:
data_2 = data.copy()

from sklearn.preprocessing import Binarizer
X = data_2.iloc[:,0].values.reshape(-1,1)                     #类为特征专用  不能使用一维数组
transformer = Binarizer(threshold=30).fit_transform(X)        #将年龄二值化以30为界限，大于为1，小于或等于为0

transformer[:20]

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [79]:
from sklearn.preprocessing import KBinsDiscretizer

X = data.iloc[:,0].values.reshape(-1,1)          #data第0列  

In [80]:
est = KBinsDiscretizer(n_bins = 3,encode='ordinal',strategy='uniform')   #默认n_bins为5
est.fit_transform(X)

set(est.fit_transform(X).ravel())

{0.0, 1.0, 2.0}

In [81]:
est = KBinsDiscretizer(n_bins = 3, encode='onehot',strategy='uniform')

est.fit_transform(X).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [2]:
import pandas as pd
data = pd.read_csv(r"D:\meachinelearn\菜菜sklearn\03数据预处理和特征工程\digit recognizor.csv")

X = data.iloc[:,1:]
Y = data.iloc[:,0]

X.shape

(42000, 784)

In [4]:
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold()               #实例化 不填参数默认方差为0
X_var0 = selector.fit_transform(X)           #删除方差为0的特征之后的新特征矩阵

X_var0.shape

(42000, 708)

In [8]:
import numpy as np
X_fsvar = VarianceThreshold(np.median(X.var().values)).fit_transform(X)  #取中位数作为阈值，减去一半的特征
X.var().values

np.median(X.var().values)

X_fsvar.shape  

(42000, 392)

In [9]:
x_bvar = VarianceThreshold(.8*(1-.8)).fit_transform(X)
x_bvar.shape

(42000, 685)

In [17]:
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.model_selection import cross_val_score
import numpy as np

X = data.iloc[:,1:]
Y = data.iloc[:,0]
X_fsvar = VarianceThreshold(np.median(X.var().values)).fit_transform(X)